version: '3.8'

services:
  db:
    container_name: gadget-room-postgres
    image: postgres:14
    environment:
      POSTGRES_DB: gadgetroom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
    ports:
      - "5544:5432"
    volumes:
      - gadget-room-volume:/var/lib/postgresql/data

volumes:
  gadget-room-volume: