services:
  shop:
    build:
      context: .
      args:
        MAVEN_PROFILE: ${MAVEN_PROFILE:-prod}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      image-storage:
        condition: service_started
    ports:
      - "${PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      JWT_REMEMBER_ME_REFRESH_TOKEN_EXPIRATION: ${JWT_REMEMBER_ME_REFRESH_TOKEN_EXPIRATION}
      JWT_RESET_TOKEN_EXPIRATION: ${JWT_RESET_TOKEN_EXPIRATION}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_RESET_SECRET: ${JWT_RESET_SECRET}
      PORT: 8080
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      MINIO_URL: http://image-storage:9000
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_MAX_CACHE_AGE: ${CORS_MAX_CACHE_AGE}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD:-}
      GMAIL_USERNAME: ${GMAIL_USERNAME:-}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    networks:
      - gadget-room-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - gadget-room-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gadget-room-network

  redis:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - gadget-room-redis-volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gadget-room-network

  image-storage:
    image: minio/minio
    ports:
      - "${MINIO_STORAGE_PORT}:9000"
      - "${MINIO_STORAGE_WEB_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - gadget-room-minio-volume:/data
    networks:
      - gadget-room-network

volumes:
  gadget-room-postgres-volume:
  gadget-room-redis-volume:
  gadget-room-minio-volume:

networks:
  gadget-room-network:
    driver: bridge
