ALTER TABLE users
    ALTER COLUMN first_name TYPE VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN last_name TYPE VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN city TYPE VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN phone_number TYPE VARCHAR(13);