CREATE TABLE product_reviews
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    fk_phone_id BIGINT                                  NOT NULL,
    fk_user_id  BIGINT                                  NOT NULL,
    rating      INTEGER                                 NOT NULL,
    comment     VARCHAR(1000),
    CONSTRAINT pk_product_reviews PRIMARY KEY (id),
    CONSTRAINT uk_product_reviews_user_phone UNIQUE (fk_user_id, fk_phone_id),
    CONSTRAINT fk_product_reviews_phone FOREIGN KEY (fk_phone_id) REFERENCES phones (id),
    CONSTRAINT fk_product_reviews_user FOREIGN KEY (fk_user_id) REFERENCES users (id),
    CONSTRAINT chk_product_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_product_reviews_phone ON product_reviews (fk_phone_id);
